//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Detail
    {
        public int OrderID { get; set; }
        public int ProductId { get; set; }
        public int OrderDetailsId { get; set; }

        public string Size { get; set; }
        public string  Color { get; set; }

        public string ProductName { get; set; }
        public string UserID { get; set; }

        public string OrderDate { get; set; }
        

        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
