//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Detail
    {
        public int OrderID { get; set; }
        public int ProductId { get; set; }
        public int OrderDetailsId { get; set; }
   

        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
        public string OrderDate { get; internal set; }
        public string ParentsCategoryName { get; internal set; }
        public string PuductorName { get; internal set; }
        public int Amount { get; internal set; }
        public string Size { get; internal set; }
        public string Color { get; internal set; }
        public string OrderNumber { get; internal set; }
        public string UserId { get; internal set; }
        public int Price { get; internal set; }
    }
}
